variables:
  MYSQL_DATABASE: 'michaesl_public'
  MYSQL_USER: 'michaesl_public'
  MYSQL_ROOT_PASSWORD: '0987654321' #burde lagres ett annet sted
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

test:
  image: node:latest
  services:
    - mysql:5 # The JS mysql-library does not yet support the newest mysql protocol
  script:
    - npm install -g flow-bin
    - cd server && npm install && npm test && flow check src
    - cd ../client && npm install && npm test && flow check src
